name: Maven Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Configure GPG Key
      run: |
       export GPG_TTY=$(tty) 
       mkdir -p ~/.gnupg/
       printf "$GPG_PRIVATE_KEY" | base64 --decode > ~/.gnupg/private.key
       gpg --batch --import ~/.gnupg/private.key
      env:
       GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}      

    - name: Publish to Apache Maven Central
      run: |
        export GPG_TTY=$(tty)
        mvn deploy -P release -Dgpg.passphrase="$GPG_PASSPHRASE"
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
